### ISSUE TITLE
Authentication through token instead of user/pass

### ISSUE THREAD

**Issue by benbouillet** [splSM/spl2smIntegration#1]
Hi Aaron !

Thanks a lot for your plugin. We're trying to implement it in our company, but the thing is that our API doesn't work with a user/pass authentication but _via_ token auth.
Would you be so kind to provide a version adapted to token authentication please ?

We use the plugin to interact with HPSaw Solution.

In our **specific** case, we use the following payloads in two (curl) calls : 
* Getting the authentication token
> curl 
> -X POST 
> -H "Authorization: Basic ###TOKEN_HERE###" 
> -d "grant_type=password&username=###USER###&password=###PASSWORD###&scope=openid profile" "###OPENID_URL###"
* Calling (posting on) the API :
> curl 
> --request POST \
> --url '###API_URL###' \
>  --header 'authorization: Bearer ###PUTTOKENHERE###' \
>  --header 'cache-control: no-cache' \
>  --header 'content-type: application/json' \
>  --header 'x-api-key: ###API_KEY###' \
>  --data '{\n"Description":"TEST INCIDENT SMA-X",
 \n"DisplayLabel":"TEST SMA-X",\n"Urgency":"SlightDisruption",\n"ImpactScope":"MultipleUsers",\n"RegisteredForActualService":83202,\n"ServiceDeskGroup":15266,\n"OwnedByPerson":6809389\n}' 

Thanks in advance !

Ben.

**Comment by splSM** [comment]
Hey Ben,

Wow, I didn’t even see this issue get logged. Need to set up notifications...

I know exactly what you’re talking about - I hooked up Splunk to a SAW instance a while ago, in fact. Let me take a look at this as soon as I can, and see what I can help with. :)

Question: Is it the just the auth that is different? The JSON payload and all the rest as they are would work fine for your SAW instance?

**Comment by splSM** [comment]
>Hi Aaron ! ...

@benbouillet Sorry this took so long - life and work got in the way and I haven’t been able to dig into this too much. The python script which performs the auto-ticketing is written specifically for SM’s API and would need a complete re-write to do this with SAW. I don’t have a SAW instance at my disposal to use in re-writing it, I’m afraid. If this is something important to your stakeholders, I’d be open to a short-term gig where I come in and integrate Splunk with your ITSM tool. Just drop me a line at splunk.consultant@outlook.com if you’re interested. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by splSM** [comment]
Closing this issue as out of scope for a Splunk to Service Manager integration.
